[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "geoparticle-tutorial"
version = "1.0.2"
authors = [{name = "Hong Zhu", email = "hzhu1@stu.suda.edu.cn"}]
dynamic = ["version", "description"]
